// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD94TElPy-ITW-KJHAMVd-ZERFIyIGMPY8',
    appId: '1:519932122801:web:a28f6e505d3d2ca986b490',
    messagingSenderId: '519932122801',
    projectId: 'j2i-app-barbearia',
    authDomain: 'j2i-app-barbearia.firebaseapp.com',
    storageBucket: 'j2i-app-barbearia.firebasestorage.app',
    measurementId: 'G-KZH5XJT3R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLZCXFkt95TSN6pivcwgsooMwgoQ0i3QE',
    appId: '1:519932122801:android:5c1f8af6a065e1b386b490',
    messagingSenderId: '519932122801',
    projectId: 'j2i-app-barbearia',
    storageBucket: 'j2i-app-barbearia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqr5gKWP-LNdDJzBimglBAh8673QSZldI',
    appId: '1:519932122801:ios:1ab7a0648de29e2886b490',
    messagingSenderId: '519932122801',
    projectId: 'j2i-app-barbearia',
    storageBucket: 'j2i-app-barbearia.firebasestorage.app',
    iosBundleId: 'com.example.j2iAppBarbearia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqr5gKWP-LNdDJzBimglBAh8673QSZldI',
    appId: '1:519932122801:ios:1ab7a0648de29e2886b490',
    messagingSenderId: '519932122801',
    projectId: 'j2i-app-barbearia',
    storageBucket: 'j2i-app-barbearia.firebasestorage.app',
    iosBundleId: 'com.example.j2iAppBarbearia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD94TElPy-ITW-KJHAMVd-ZERFIyIGMPY8',
    appId: '1:519932122801:web:83216d44f0891c3c86b490',
    messagingSenderId: '519932122801',
    projectId: 'j2i-app-barbearia',
    authDomain: 'j2i-app-barbearia.firebaseapp.com',
    storageBucket: 'j2i-app-barbearia.firebasestorage.app',
    measurementId: 'G-QCB85ZG4J0',
  );
}
